//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cofradia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reuniones
    {
        public int idReunion { get; set; }
        public Nullable<System.DateTime> fechaReunion { get; set; }
        public string temaReunion { get; set; }
    }
}
